languageCode = "en"
title = "Batjaa's corner"
theme = "mongkok"
DefaultContentLanguage = "en"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Batjaa Batbold"
    favicon = "https://secure.gravatar.com/avatar/44f8f75c884a13de29f4a310083cd82e?s=16"
    email = "batjaa.batbold@gmail.com"
    phone = "+1 804 505 0615"
    signature = "Batjargal Batbold"
    address = "Palo Alto, California, USA"
    website = "batjaa.com"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[taxonomies]
  category = "categories"
  portfolio = "portfolios"
  tag = "tags"

staticDir = "static"

[languages]
  [languages.en]
    baseURL = "https://batjaa.com"
    languageName = "English"
    staticDir2 = "static_en"
    title = "Batjaa's corner"
    weight = 1
    [languages.en.params]
        resume = "Batjargal Batbold -- Software Engineer.pdf"

  [languages.mn]
    baseURL = "https://batjargal.mn"
    languageName = "Mongolian"
    staticDir3 = "static_mn"
    title = "Батжаагийн булан"
    weight = 2
    [languages.mn.params]
      signature = "Батболдын Батжаргал"
      resume = "Batjargal Batbold -- Program hangamjiin engineer.pdf"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

# Social

[[params.social]]
  url = ""
  name = "facebook"
  icon = "fa-facebook"
  hover = "&#xf09a;"
  weight = 1
[[params.social]]
  url = "https://twitter.com/batjaabatbold/"
  name = "twitter"
  icon = "fa-twitter"
  hover = "&#xf099;"
  weight = 1
[[params.social]]
  url = "https://www.linkedin.com/in/batjargalbatbold/"
  name = "linkedin"
  icon = "fa-linkedin"
  hover = "&#xf0e1;"
  weight = 1
[[params.social]]
  url = ""
  name = "dribbble"
  icon = "fa-dribbble"
  hover = "&#xf17d;"
  weight = 1
[[params.social]]
  url = ""
  name = "pinterest"
  icon = "fa-pinterest"
  hover = "&#xf0d2;"
  weight = 1
[[params.social]]
  url = ""
  name = "flickr"
  icon = "fa-flickr"
  hover = "&#xf16e;"
  weight = 1
[[params.social]]
  url = ""
  name = "weibo"
  icon = "fa-weibo"
  hover = "&#xf18a;"
  weight = 1
[[params.social]]
  url = "https://github.com/batjaa/"
  name = "github"
  icon = "fa-github"
  hover = "&#xf09b;"
  weight = 19
[[params.social]]
  url = "https://www.instagram.com/batjaa.batbold/"
  name = "instagram"
  icon = "fa-instagram"
  hover = "&#xf16d;"
  weight = 20
[[params.social]]
  url = "https://stackoverflow.com/story/batjaa"
  name = "stack-overflow"
  icon = "fa-stack-overflow"
  hover = "&#xf16c;"
  weight = 1
[[params.social]]
  url = ""
  name = "tumblr"
  icon = "fa-tumblr"
  hover = "&#xf173;"
  weight = 1
[[params.social]]
  url = "skype:batjaa_10"
  name = "skype"
  icon = "fa-skype"
  hover = "&#xf17e;"
  weight = 1
[[params.social]]
  url = ""
  name = "vimeo-square"
  icon = "fa-vimeo"
  hover = "&#xf194;"
  weight = 1
[[params.social]]
  url = ""
  name = "xing"
  icon = "fa-xing"
  hover = "&#xf168;"
  weight = 1
[[params.social]]
  url = ""
  name = "dropbox"
  icon = "fa-dropbox"
  hover = "&#xf16b;"
  weight = 1
[[params.social]]
  url = ""
  name = "rss"
  icon = "fa-rss"
  hover = "&#xf09e;"
  weight = 1
[[params.social]]
  url = ""
  name = "foursquare"
  icon = "fa-foursquare"
  hover = "&#xf180;"
  weight = 1
[[params.social]]
  url = "https://vk.com/batjaa"
  name = "vk"
  icon = "fa-vk"
  hover = "&#xf189;"
  weight = 1
[[params.social]]
  url = ""
  name = "renren"
  icon = "fa-renren"
  hover = "&#xf18b;"
  weight = 1
[[params.social]]
  url = "https://www.youtube.com/c/BatjargalBatbold"
  name = "youtube"
  icon = "fa-youtube"
  hover = "&#xf167;"
  weight = 19