baseURL = "http://example.com/"
languageCode = "en-us"
title = "Minimal"
theme = "mongkok"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Batjaa Batbold"
    signature = "Batjargal Batbold"
    description = "Engineer & Travel/Photo/Video/Coffee Enthusiast"
    favicon = "https://secure.gravatar.com/avatar/44f8f75c884a13de29f4a310083cd82e?s=16"
    githubUsername = "#batjaa"
    email = "batjaa.batbold@gmail.com"
    phone = "+1 804 505 0615"
    website = "batjaa.com"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[taxonomies]
  category = "categories"
  portfolio = "portfolios"
  tag = "tags"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:batjaa.batbold@gmail.com"
    name = "envelope-o"
    weight = 1

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

# Social

[[params.social]]
  url = ""
  name = "facebook"
  icon = "fa-facebook"
  hover = "&#xf09a;"
  weight = 1
[[params.social]]
  url = "https://twitter.com/batjaabatbold/"
  name = "twitter"
  icon = "fa-twitter"
  hover = "&#xf099;"
  weight = 1
[[params.social]]
  url = "https://www.linkedin.com/in/batjargalbatbold/"
  name = "linkedin"
  icon = "fa-linkedin"
  hover = "&#xf0e1;"
  weight = 1
[[params.social]]
  url = ""
  name = "dribbble"
  icon = "fa-dribbble"
  hover = "&#xf17d;"
  weight = 1
[[params.social]]
  url = ""
  name = "pinterest"
  icon = "fa-pinterest"
  hover = "&#xf0d2;"
  weight = 1
[[params.social]]
  url = ""
  name = "flickr"
  icon = "fa-flickr"
  hover = "&#xf16e;"
  weight = 1
[[params.social]]
  url = ""
  name = "weibo"
  icon = "fa-weibo"
  hover = "&#xf18a;"
  weight = 1
[[params.social]]
  url = "https://github.com/batjaa/"
  name = "github"
  icon = "fa-github"
  hover = "&#xf09b;"
  weight = 19
[[params.social]]
  url = "https://www.instagram.com/batjaa.batbold/"
  name = "instagram"
  icon = "fa-instagram"
  hover = "&#xf16d;"
  weight = 20
[[params.social]]
  url = "https://stackoverflow.com/story/batjaa"
  name = "stack-overflow"
  icon = "fa-stack-overflow"
  hover = "&#xf16c;"
  weight = 1
[[params.social]]
  url = ""
  name = "tumblr"
  icon = "fa-tumblr"
  hover = "&#xf173;"
  weight = 1
[[params.social]]
  url = "skype:batjaa_10"
  name = "skype"
  icon = "fa-skype"
  hover = "&#xf17e;"
  weight = 1
[[params.social]]
  url = ""
  name = "vimeo-square"
  icon = "fa-vimeo"
  hover = "&#xf194;"
  weight = 1
[[params.social]]
  url = ""
  name = "xing"
  icon = "fa-xing"
  hover = "&#xf168;"
  weight = 1
[[params.social]]
  url = ""
  name = "dropbox"
  icon = "fa-dropbox"
  hover = "&#xf16b;"
  weight = 1
[[params.social]]
  url = ""
  name = "rss"
  icon = "fa-rss"
  hover = "&#xf09e;"
  weight = 1
[[params.social]]
  url = ""
  name = "foursquare"
  icon = "fa-foursquare"
  hover = "&#xf180;"
  weight = 1
[[params.social]]
  url = "https://vk.com/batjaa"
  name = "vk"
  icon = "fa-vk"
  hover = "&#xf189;"
  weight = 1
[[params.social]]
  url = ""
  name = "renren"
  icon = "fa-renren"
  hover = "&#xf18b;"
  weight = 1
[[params.social]]
  url = "https://www.youtube.com/c/BatjargalBatbold"
  name = "youtube"
  icon = "fa-youtube"
  hover = "&#xf167;"
  weight = 19